apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: out-cluster
  name: out-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: out-cluster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: out-cluster
    spec:
      containers:
      - image: santoshdts/out-cluster:0.1.0
        name: out-cluster
        resources: {}
status: {}
